
<Window>:

    obstacle:  obstacle
    ball:  ball
    Obstacle:
        id:  obstacle
    Ball:
        id:  ball

    Label:
        font_size:  20
        text:  'physics environment'
        pos:  root.center_x - 50, root.center_y * 1.5

<Ball>:
    size:  50, 50
    canvas:
        Ellipse:
            pos:  self.pos
            size: self.size

<Obstacle>:
    size:  50, 50
    pos:  600, 200
    canvas:
        Rectangle:
            size:  self.size
            pos:  self.pos
